### ISSUE TITLE
Bitte styleissues fixen

### ISSUE THREAD

**Issue by rassaei** [hhu-propra2/abschlussprojekt-perfectlybalanced#79]
> Task :checkstyleMain
[ant:checkstyle] [WARN] /home/sam/code/propra/src/main/java/de/hhu/abschlussprojektverleihplattform/service/ILendingService.java:43: Zeile ist 105 Zeichen lang (Obergrenze ist 100). [LineLength]
[ant:checkstyle] [WARN] /home/sam/code/propra/src/main/java/de/hhu/abschlussprojektverleihplattform/service/LendingService.java:268: Zeile ist 110 Zeichen lang (Obergrenze ist 100). [LineLength]
[ant:checkstyle] [WARN] /home/sam/code/propra/src/main/java/de/hhu/abschlussprojektverleihplattform/service/LendingService.java:274: Zeile ist 111 Zeichen lang (Obergrenze ist 100). [LineLength]

**Comment by Sonic4080** [comment]
sind lokal gelöst, kommen in meinen nächste PR
