### ISSUE TITLE
Suspicious  comparison of Long references in  de.hhu.abschlussprojektverleihplattform.testdummys.PaymentServiceDummy.findReservation(Long)

### ISSUE THREAD

**Issue by rassaei** [hhu-propra2/abschlussprojekt-perfectlybalanced#87]
> Bug type RC_REF_COMPARISON (click for details) In class de.hhu.abschlussprojektverleihplattform.testdummys.PaymentServiceDummyIn method de.hhu.abschlussprojektverleihplattform.testdummys.PaymentServiceDummy.findReservation(Long)Actual type LongValue loaded from idReturn value of de.hhu.abschlussprojektverleihplattform.testdummys.ReservationDummy.getId() of type LongAt PaymentServiceDummy.java:[line 85]

**Comment by rassaei** [comment]
This method compares two reference values using the == or != operator, where the correct way to compare instances of this type is generally with the equals() method. It is possible to create distinct instances that are equal but do not compare as == since they are different objects. Examples of classes which should generally not be compared by reference are java.lang.Integer, java.lang.Float, etc.

**Comment by pointbazaar** [comment]
Spotbugs hat sich gelohnt

**Comment by Sonic4080** [comment]
wird mit meinem nächten PR gelöst
